// Auto-generated biology terms header file
BioTerm extended_dictionary[] = {
    {"apoptosis_1", "Apoptosis is the process of programmed cell death."},
    {"apoptosis_2", "Apoptosis is the process of programmed cell death."},
    {"mitochondria_3", "Mitochondria are known as the powerhouse of the cell."},
    {"nucleotide_4", "A nucleotide is the basic building block of DNA and RNA."},
    {"translation_5", "Translation is the process where ribosomes create proteins using mRNA."},
    {"biome_6", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"biome_7", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"translation_8", "Translation is the process where ribosomes create proteins using mRNA."},
    {"chloroplast_9", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"transcription_10", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"biome_11", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"nucleotide_12", "A nucleotide is the basic building block of DNA and RNA."},
    {"nucleotide_13", "A nucleotide is the basic building block of DNA and RNA."},
    {"chloroplast_14", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"mitochondria_15", "Mitochondria are known as the powerhouse of the cell."},
    {"apoptosis_16", "Apoptosis is the process of programmed cell death."},
    {"antigen_17", "An antigen is a substance that induces an immune response."},
    {"translation_18", "Translation is the process where ribosomes create proteins using mRNA."},
    {"mitochondria_19", "Mitochondria are known as the powerhouse of the cell."},
    {"ecosystem_20", "An ecosystem is a community of living organisms interacting with their environment."},
    {"ecosystem_21", "An ecosystem is a community of living organisms interacting with their environment."},
    {"nucleotide_22", "A nucleotide is the basic building block of DNA and RNA."},
    {"biome_23", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"biome_24", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"translation_25", "Translation is the process where ribosomes create proteins using mRNA."},
    {"chloroplast_26", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"antibody_27", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"antibody_28", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"nucleotide_29", "A nucleotide is the basic building block of DNA and RNA."},
    {"nucleotide_30", "A nucleotide is the basic building block of DNA and RNA."},
    {"mitochondria_31", "Mitochondria are known as the powerhouse of the cell."},
    {"nucleotide_32", "A nucleotide is the basic building block of DNA and RNA."},
    {"transcription_33", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"mitochondria_34", "Mitochondria are known as the powerhouse of the cell."},
    {"apoptosis_35", "Apoptosis is the process of programmed cell death."},
    {"biome_36", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"transcription_37", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antibody_38", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"nucleotide_39", "A nucleotide is the basic building block of DNA and RNA."},
    {"chloroplast_40", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"antigen_41", "An antigen is a substance that induces an immune response."},
    {"apoptosis_42", "Apoptosis is the process of programmed cell death."},
    {"antigen_43", "An antigen is a substance that induces an immune response."},
    {"chloroplast_44", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"translation_45", "Translation is the process where ribosomes create proteins using mRNA."},
    {"mitochondria_46", "Mitochondria are known as the powerhouse of the cell."},
    {"ecosystem_47", "An ecosystem is a community of living organisms interacting with their environment."},
    {"mitochondria_48", "Mitochondria are known as the powerhouse of the cell."},
    {"apoptosis_49", "Apoptosis is the process of programmed cell death."},
    {"apoptosis_50", "Apoptosis is the process of programmed cell death."},
    {"translation_51", "Translation is the process where ribosomes create proteins using mRNA."},
    {"transcription_52", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"apoptosis_53", "Apoptosis is the process of programmed cell death."},
    {"antigen_54", "An antigen is a substance that induces an immune response."},
    {"antibody_55", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"ecosystem_56", "An ecosystem is a community of living organisms interacting with their environment."},
    {"nucleotide_57", "A nucleotide is the basic building block of DNA and RNA."},
    {"mitochondria_58", "Mitochondria are known as the powerhouse of the cell."},
    {"apoptosis_59", "Apoptosis is the process of programmed cell death."},
    {"ecosystem_60", "An ecosystem is a community of living organisms interacting with their environment."},
    {"ecosystem_61", "An ecosystem is a community of living organisms interacting with their environment."},
    {"antigen_62", "An antigen is a substance that induces an immune response."},
    {"nucleotide_63", "A nucleotide is the basic building block of DNA and RNA."},
    {"antibody_64", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"nucleotide_65", "A nucleotide is the basic building block of DNA and RNA."},
    {"mitochondria_66", "Mitochondria are known as the powerhouse of the cell."},
    {"ecosystem_67", "An ecosystem is a community of living organisms interacting with their environment."},
    {"translation_68", "Translation is the process where ribosomes create proteins using mRNA."},
    {"biome_69", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"transcription_70", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"nucleotide_71", "A nucleotide is the basic building block of DNA and RNA."},
    {"chloroplast_72", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"transcription_73", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antigen_74", "An antigen is a substance that induces an immune response."},
    {"biome_75", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"antigen_76", "An antigen is a substance that induces an immune response."},
    {"translation_77", "Translation is the process where ribosomes create proteins using mRNA."},
    {"ecosystem_78", "An ecosystem is a community of living organisms interacting with their environment."},
    {"biome_79", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"chloroplast_80", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"mitochondria_81", "Mitochondria are known as the powerhouse of the cell."},
    {"ecosystem_82", "An ecosystem is a community of living organisms interacting with their environment."},
    {"mitochondria_83", "Mitochondria are known as the powerhouse of the cell."},
    {"transcription_84", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"mitochondria_85", "Mitochondria are known as the powerhouse of the cell."},
    {"biome_86", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"nucleotide_87", "A nucleotide is the basic building block of DNA and RNA."},
    {"chloroplast_88", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"transcription_89", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antibody_90", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"nucleotide_91", "A nucleotide is the basic building block of DNA and RNA."},
    {"nucleotide_92", "A nucleotide is the basic building block of DNA and RNA."},
    {"chloroplast_93", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"biome_94", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"translation_95", "Translation is the process where ribosomes create proteins using mRNA."},
    {"translation_96", "Translation is the process where ribosomes create proteins using mRNA."},
    {"chloroplast_97", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"transcription_98", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antigen_99", "An antigen is a substance that induces an immune response."},
    {"antibody_100", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"antigen_101", "An antigen is a substance that induces an immune response."},
    {"antibody_102", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"chloroplast_103", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"biome_104", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"nucleotide_105", "A nucleotide is the basic building block of DNA and RNA."},
    {"nucleotide_106", "A nucleotide is the basic building block of DNA and RNA."},
    {"nucleotide_107", "A nucleotide is the basic building block of DNA and RNA."},
    {"nucleotide_108", "A nucleotide is the basic building block of DNA and RNA."},
    {"translation_109", "Translation is the process where ribosomes create proteins using mRNA."},
    {"transcription_110", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"translation_111", "Translation is the process where ribosomes create proteins using mRNA."},
    {"ecosystem_112", "An ecosystem is a community of living organisms interacting with their environment."},
    {"apoptosis_113", "Apoptosis is the process of programmed cell death."},
    {"transcription_114", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"nucleotide_115", "A nucleotide is the basic building block of DNA and RNA."},
    {"transcription_116", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antigen_117", "An antigen is a substance that induces an immune response."},
    {"translation_118", "Translation is the process where ribosomes create proteins using mRNA."},
    {"antibody_119", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"mitochondria_120", "Mitochondria are known as the powerhouse of the cell."},
    {"translation_121", "Translation is the process where ribosomes create proteins using mRNA."},
    {"transcription_122", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"translation_123", "Translation is the process where ribosomes create proteins using mRNA."},
    {"nucleotide_124", "A nucleotide is the basic building block of DNA and RNA."},
    {"biome_125", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"ecosystem_126", "An ecosystem is a community of living organisms interacting with their environment."},
    {"translation_127", "Translation is the process where ribosomes create proteins using mRNA."},
    {"apoptosis_128", "Apoptosis is the process of programmed cell death."},
    {"mitochondria_129", "Mitochondria are known as the powerhouse of the cell."},
    {"antigen_130", "An antigen is a substance that induces an immune response."},
    {"translation_131", "Translation is the process where ribosomes create proteins using mRNA."},
    {"mitochondria_132", "Mitochondria are known as the powerhouse of the cell."},
    {"transcription_133", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antigen_134", "An antigen is a substance that induces an immune response."},
    {"antigen_135", "An antigen is a substance that induces an immune response."},
    {"nucleotide_136", "A nucleotide is the basic building block of DNA and RNA."},
    {"mitochondria_137", "Mitochondria are known as the powerhouse of the cell."},
    {"nucleotide_138", "A nucleotide is the basic building block of DNA and RNA."},
    {"ecosystem_139", "An ecosystem is a community of living organisms interacting with their environment."},
    {"translation_140", "Translation is the process where ribosomes create proteins using mRNA."},
    {"transcription_141", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"biome_142", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"nucleotide_143", "A nucleotide is the basic building block of DNA and RNA."},
    {"mitochondria_144", "Mitochondria are known as the powerhouse of the cell."},
    {"apoptosis_145", "Apoptosis is the process of programmed cell death."},
    {"chloroplast_146", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"nucleotide_147", "A nucleotide is the basic building block of DNA and RNA."},
    {"chloroplast_148", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"chloroplast_149", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"ecosystem_150", "An ecosystem is a community of living organisms interacting with their environment."},
    {"ecosystem_151", "An ecosystem is a community of living organisms interacting with their environment."},
    {"ecosystem_152", "An ecosystem is a community of living organisms interacting with their environment."},
    {"biome_153", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"biome_154", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"apoptosis_155", "Apoptosis is the process of programmed cell death."},
    {"transcription_156", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antibody_157", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"biome_158", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"apoptosis_159", "Apoptosis is the process of programmed cell death."},
    {"apoptosis_160", "Apoptosis is the process of programmed cell death."},
    {"antigen_161", "An antigen is a substance that induces an immune response."},
    {"translation_162", "Translation is the process where ribosomes create proteins using mRNA."},
    {"ecosystem_163", "An ecosystem is a community of living organisms interacting with their environment."},
    {"chloroplast_164", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"antibody_165", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"apoptosis_166", "Apoptosis is the process of programmed cell death."},
    {"chloroplast_167", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"mitochondria_168", "Mitochondria are known as the powerhouse of the cell."},
    {"ecosystem_169", "An ecosystem is a community of living organisms interacting with their environment."},
    {"antibody_170", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"apoptosis_171", "Apoptosis is the process of programmed cell death."},
    {"mitochondria_172", "Mitochondria are known as the powerhouse of the cell."},
    {"mitochondria_173", "Mitochondria are known as the powerhouse of the cell."},
    {"transcription_174", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"translation_175", "Translation is the process where ribosomes create proteins using mRNA."},
    {"antibody_176", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"transcription_177", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"ecosystem_178", "An ecosystem is a community of living organisms interacting with their environment."},
    {"apoptosis_179", "Apoptosis is the process of programmed cell death."},
    {"transcription_180", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"chloroplast_181", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"apoptosis_182", "Apoptosis is the process of programmed cell death."},
    {"biome_183", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"nucleotide_184", "A nucleotide is the basic building block of DNA and RNA."},
    {"translation_185", "Translation is the process where ribosomes create proteins using mRNA."},
    {"nucleotide_186", "A nucleotide is the basic building block of DNA and RNA."},
    {"biome_187", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"biome_188", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"mitochondria_189", "Mitochondria are known as the powerhouse of the cell."},
    {"biome_190", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"chloroplast_191", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"nucleotide_192", "A nucleotide is the basic building block of DNA and RNA."},
    {"mitochondria_193", "Mitochondria are known as the powerhouse of the cell."},
    {"ecosystem_194", "An ecosystem is a community of living organisms interacting with their environment."},
    {"mitochondria_195", "Mitochondria are known as the powerhouse of the cell."},
    {"ecosystem_196", "An ecosystem is a community of living organisms interacting with their environment."},
    {"antibody_197", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"transcription_198", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"nucleotide_199", "A nucleotide is the basic building block of DNA and RNA."},
    {"translation_200", "Translation is the process where ribosomes create proteins using mRNA."},
    {"chloroplast_201", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"nucleotide_202", "A nucleotide is the basic building block of DNA and RNA."},
    {"nucleotide_203", "A nucleotide is the basic building block of DNA and RNA."},
    {"mitochondria_204", "Mitochondria are known as the powerhouse of the cell."},
    {"ecosystem_205", "An ecosystem is a community of living organisms interacting with their environment."},
    {"chloroplast_206", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"antigen_207", "An antigen is a substance that induces an immune response."},
    {"antigen_208", "An antigen is a substance that induces an immune response."},
    {"chloroplast_209", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"transcription_210", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"mitochondria_211", "Mitochondria are known as the powerhouse of the cell."},
    {"ecosystem_212", "An ecosystem is a community of living organisms interacting with their environment."},
    {"nucleotide_213", "A nucleotide is the basic building block of DNA and RNA."},
    {"chloroplast_214", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"biome_215", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"chloroplast_216", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"ecosystem_217", "An ecosystem is a community of living organisms interacting with their environment."},
    {"ecosystem_218", "An ecosystem is a community of living organisms interacting with their environment."},
    {"transcription_219", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"apoptosis_220", "Apoptosis is the process of programmed cell death."},
    {"transcription_221", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antigen_222", "An antigen is a substance that induces an immune response."},
    {"nucleotide_223", "A nucleotide is the basic building block of DNA and RNA."},
    {"ecosystem_224", "An ecosystem is a community of living organisms interacting with their environment."},
    {"translation_225", "Translation is the process where ribosomes create proteins using mRNA."},
    {"ecosystem_226", "An ecosystem is a community of living organisms interacting with their environment."},
    {"ecosystem_227", "An ecosystem is a community of living organisms interacting with their environment."},
    {"translation_228", "Translation is the process where ribosomes create proteins using mRNA."},
    {"antigen_229", "An antigen is a substance that induces an immune response."},
    {"mitochondria_230", "Mitochondria are known as the powerhouse of the cell."},
    {"antibody_231", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"nucleotide_232", "A nucleotide is the basic building block of DNA and RNA."},
    {"antigen_233", "An antigen is a substance that induces an immune response."},
    {"transcription_234", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"transcription_235", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"biome_236", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"chloroplast_237", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"ecosystem_238", "An ecosystem is a community of living organisms interacting with their environment."},
    {"translation_239", "Translation is the process where ribosomes create proteins using mRNA."},
    {"nucleotide_240", "A nucleotide is the basic building block of DNA and RNA."},
    {"transcription_241", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antibody_242", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"antigen_243", "An antigen is a substance that induces an immune response."},
    {"apoptosis_244", "Apoptosis is the process of programmed cell death."},
    {"biome_245", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"ecosystem_246", "An ecosystem is a community of living organisms interacting with their environment."},
    {"chloroplast_247", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"antibody_248", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"antibody_249", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"ecosystem_250", "An ecosystem is a community of living organisms interacting with their environment."},
    {"antigen_251", "An antigen is a substance that induces an immune response."},
    {"transcription_252", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"mitochondria_253", "Mitochondria are known as the powerhouse of the cell."},
    {"apoptosis_254", "Apoptosis is the process of programmed cell death."},
    {"translation_255", "Translation is the process where ribosomes create proteins using mRNA."},
    {"chloroplast_256", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"transcription_257", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antigen_258", "An antigen is a substance that induces an immune response."},
    {"transcription_259", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"biome_260", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"biome_261", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"nucleotide_262", "A nucleotide is the basic building block of DNA and RNA."},
    {"nucleotide_263", "A nucleotide is the basic building block of DNA and RNA."},
    {"antibody_264", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"ecosystem_265", "An ecosystem is a community of living organisms interacting with their environment."},
    {"antigen_266", "An antigen is a substance that induces an immune response."},
    {"ecosystem_267", "An ecosystem is a community of living organisms interacting with their environment."},
    {"translation_268", "Translation is the process where ribosomes create proteins using mRNA."},
    {"transcription_269", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antigen_270", "An antigen is a substance that induces an immune response."},
    {"ecosystem_271", "An ecosystem is a community of living organisms interacting with their environment."},
    {"ecosystem_272", "An ecosystem is a community of living organisms interacting with their environment."},
    {"apoptosis_273", "Apoptosis is the process of programmed cell death."},
    {"chloroplast_274", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"translation_275", "Translation is the process where ribosomes create proteins using mRNA."},
    {"mitochondria_276", "Mitochondria are known as the powerhouse of the cell."},
    {"ecosystem_277", "An ecosystem is a community of living organisms interacting with their environment."},
    {"antigen_278", "An antigen is a substance that induces an immune response."},
    {"antigen_279", "An antigen is a substance that induces an immune response."},
    {"antigen_280", "An antigen is a substance that induces an immune response."},
    {"transcription_281", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"transcription_282", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"mitochondria_283", "Mitochondria are known as the powerhouse of the cell."},
    {"translation_284", "Translation is the process where ribosomes create proteins using mRNA."},
    {"nucleotide_285", "A nucleotide is the basic building block of DNA and RNA."},
    {"ecosystem_286", "An ecosystem is a community of living organisms interacting with their environment."},
    {"antigen_287", "An antigen is a substance that induces an immune response."},
    {"ecosystem_288", "An ecosystem is a community of living organisms interacting with their environment."},
    {"mitochondria_289", "Mitochondria are known as the powerhouse of the cell."},
    {"apoptosis_290", "Apoptosis is the process of programmed cell death."},
    {"chloroplast_291", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"ecosystem_292", "An ecosystem is a community of living organisms interacting with their environment."},
    {"chloroplast_293", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"antibody_294", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"translation_295", "Translation is the process where ribosomes create proteins using mRNA."},
    {"antigen_296", "An antigen is a substance that induces an immune response."},
    {"ecosystem_297", "An ecosystem is a community of living organisms interacting with their environment."},
    {"chloroplast_298", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"mitochondria_299", "Mitochondria are known as the powerhouse of the cell."},
    {"apoptosis_300", "Apoptosis is the process of programmed cell death."},
    {"chloroplast_301", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"translation_302", "Translation is the process where ribosomes create proteins using mRNA."},
    {"mitochondria_303", "Mitochondria are known as the powerhouse of the cell."},
    {"ecosystem_304", "An ecosystem is a community of living organisms interacting with their environment."},
    {"apoptosis_305", "Apoptosis is the process of programmed cell death."},
    {"mitochondria_306", "Mitochondria are known as the powerhouse of the cell."},
    {"nucleotide_307", "A nucleotide is the basic building block of DNA and RNA."},
    {"mitochondria_308", "Mitochondria are known as the powerhouse of the cell."},
    {"ecosystem_309", "An ecosystem is a community of living organisms interacting with their environment."},
    {"transcription_310", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"nucleotide_311", "A nucleotide is the basic building block of DNA and RNA."},
    {"mitochondria_312", "Mitochondria are known as the powerhouse of the cell."},
    {"mitochondria_313", "Mitochondria are known as the powerhouse of the cell."},
    {"biome_314", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"biome_315", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"ecosystem_316", "An ecosystem is a community of living organisms interacting with their environment."},
    {"mitochondria_317", "Mitochondria are known as the powerhouse of the cell."},
    {"antibody_318", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"transcription_319", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"mitochondria_320", "Mitochondria are known as the powerhouse of the cell."},
    {"nucleotide_321", "A nucleotide is the basic building block of DNA and RNA."},
    {"antibody_322", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"translation_323", "Translation is the process where ribosomes create proteins using mRNA."},
    {"antigen_324", "An antigen is a substance that induces an immune response."},
    {"mitochondria_325", "Mitochondria are known as the powerhouse of the cell."},
    {"mitochondria_326", "Mitochondria are known as the powerhouse of the cell."},
    {"translation_327", "Translation is the process where ribosomes create proteins using mRNA."},
    {"mitochondria_328", "Mitochondria are known as the powerhouse of the cell."},
    {"antigen_329", "An antigen is a substance that induces an immune response."},
    {"biome_330", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"nucleotide_331", "A nucleotide is the basic building block of DNA and RNA."},
    {"antibody_332", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"antigen_333", "An antigen is a substance that induces an immune response."},
    {"transcription_334", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"biome_335", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"ecosystem_336", "An ecosystem is a community of living organisms interacting with their environment."},
    {"chloroplast_337", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"apoptosis_338", "Apoptosis is the process of programmed cell death."},
    {"ecosystem_339", "An ecosystem is a community of living organisms interacting with their environment."},
    {"ecosystem_340", "An ecosystem is a community of living organisms interacting with their environment."},
    {"nucleotide_341", "A nucleotide is the basic building block of DNA and RNA."},
    {"ecosystem_342", "An ecosystem is a community of living organisms interacting with their environment."},
    {"nucleotide_343", "A nucleotide is the basic building block of DNA and RNA."},
    {"translation_344", "Translation is the process where ribosomes create proteins using mRNA."},
    {"nucleotide_345", "A nucleotide is the basic building block of DNA and RNA."},
    {"antigen_346", "An antigen is a substance that induces an immune response."},
    {"translation_347", "Translation is the process where ribosomes create proteins using mRNA."},
    {"antibody_348", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"biome_349", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"nucleotide_350", "A nucleotide is the basic building block of DNA and RNA."},
    {"chloroplast_351", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"antigen_352", "An antigen is a substance that induces an immune response."},
    {"mitochondria_353", "Mitochondria are known as the powerhouse of the cell."},
    {"chloroplast_354", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"antigen_355", "An antigen is a substance that induces an immune response."},
    {"ecosystem_356", "An ecosystem is a community of living organisms interacting with their environment."},
    {"ecosystem_357", "An ecosystem is a community of living organisms interacting with their environment."},
    {"ecosystem_358", "An ecosystem is a community of living organisms interacting with their environment."},
    {"ecosystem_359", "An ecosystem is a community of living organisms interacting with their environment."},
    {"chloroplast_360", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"translation_361", "Translation is the process where ribosomes create proteins using mRNA."},
    {"antibody_362", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"transcription_363", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"translation_364", "Translation is the process where ribosomes create proteins using mRNA."},
    {"nucleotide_365", "A nucleotide is the basic building block of DNA and RNA."},
    {"biome_366", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"mitochondria_367", "Mitochondria are known as the powerhouse of the cell."},
    {"transcription_368", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"transcription_369", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"transcription_370", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"apoptosis_371", "Apoptosis is the process of programmed cell death."},
    {"mitochondria_372", "Mitochondria are known as the powerhouse of the cell."},
    {"chloroplast_373", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"nucleotide_374", "A nucleotide is the basic building block of DNA and RNA."},
    {"transcription_375", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"nucleotide_376", "A nucleotide is the basic building block of DNA and RNA."},
    {"apoptosis_377", "Apoptosis is the process of programmed cell death."},
    {"translation_378", "Translation is the process where ribosomes create proteins using mRNA."},
    {"antigen_379", "An antigen is a substance that induces an immune response."},
    {"mitochondria_380", "Mitochondria are known as the powerhouse of the cell."},
    {"transcription_381", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"transcription_382", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antigen_383", "An antigen is a substance that induces an immune response."},
    {"antibody_384", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"nucleotide_385", "A nucleotide is the basic building block of DNA and RNA."},
    {"chloroplast_386", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"nucleotide_387", "A nucleotide is the basic building block of DNA and RNA."},
    {"transcription_388", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antibody_389", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"antigen_390", "An antigen is a substance that induces an immune response."},
    {"translation_391", "Translation is the process where ribosomes create proteins using mRNA."},
    {"transcription_392", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"ecosystem_393", "An ecosystem is a community of living organisms interacting with their environment."},
    {"chloroplast_394", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"translation_395", "Translation is the process where ribosomes create proteins using mRNA."},
    {"biome_396", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"nucleotide_397", "A nucleotide is the basic building block of DNA and RNA."},
    {"mitochondria_398", "Mitochondria are known as the powerhouse of the cell."},
    {"ecosystem_399", "An ecosystem is a community of living organisms interacting with their environment."},
    {"chloroplast_400", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"translation_401", "Translation is the process where ribosomes create proteins using mRNA."},
    {"apoptosis_402", "Apoptosis is the process of programmed cell death."},
    {"apoptosis_403", "Apoptosis is the process of programmed cell death."},
    {"biome_404", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"nucleotide_405", "A nucleotide is the basic building block of DNA and RNA."},
    {"translation_406", "Translation is the process where ribosomes create proteins using mRNA."},
    {"ecosystem_407", "An ecosystem is a community of living organisms interacting with their environment."},
    {"biome_408", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"apoptosis_409", "Apoptosis is the process of programmed cell death."},
    {"apoptosis_410", "Apoptosis is the process of programmed cell death."},
    {"transcription_411", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"ecosystem_412", "An ecosystem is a community of living organisms interacting with their environment."},
    {"apoptosis_413", "Apoptosis is the process of programmed cell death."},
    {"biome_414", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"transcription_415", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antibody_416", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"chloroplast_417", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"apoptosis_418", "Apoptosis is the process of programmed cell death."},
    {"mitochondria_419", "Mitochondria are known as the powerhouse of the cell."},
    {"biome_420", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"ecosystem_421", "An ecosystem is a community of living organisms interacting with their environment."},
    {"translation_422", "Translation is the process where ribosomes create proteins using mRNA."},
    {"ecosystem_423", "An ecosystem is a community of living organisms interacting with their environment."},
    {"antigen_424", "An antigen is a substance that induces an immune response."},
    {"transcription_425", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"transcription_426", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antigen_427", "An antigen is a substance that induces an immune response."},
    {"chloroplast_428", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"apoptosis_429", "Apoptosis is the process of programmed cell death."},
    {"antigen_430", "An antigen is a substance that induces an immune response."},
    {"nucleotide_431", "A nucleotide is the basic building block of DNA and RNA."},
    {"nucleotide_432", "A nucleotide is the basic building block of DNA and RNA."},
    {"transcription_433", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"ecosystem_434", "An ecosystem is a community of living organisms interacting with their environment."},
    {"transcription_435", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"biome_436", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"apoptosis_437", "Apoptosis is the process of programmed cell death."},
    {"transcription_438", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"translation_439", "Translation is the process where ribosomes create proteins using mRNA."},
    {"transcription_440", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antigen_441", "An antigen is a substance that induces an immune response."},
    {"apoptosis_442", "Apoptosis is the process of programmed cell death."},
    {"chloroplast_443", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"chloroplast_444", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"nucleotide_445", "A nucleotide is the basic building block of DNA and RNA."},
    {"antigen_446", "An antigen is a substance that induces an immune response."},
    {"transcription_447", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"apoptosis_448", "Apoptosis is the process of programmed cell death."},
    {"antibody_449", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"biome_450", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"antibody_451", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"mitochondria_452", "Mitochondria are known as the powerhouse of the cell."},
    {"antigen_453", "An antigen is a substance that induces an immune response."},
    {"antibody_454", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"mitochondria_455", "Mitochondria are known as the powerhouse of the cell."},
    {"ecosystem_456", "An ecosystem is a community of living organisms interacting with their environment."},
    {"biome_457", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"antigen_458", "An antigen is a substance that induces an immune response."},
    {"apoptosis_459", "Apoptosis is the process of programmed cell death."},
    {"transcription_460", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"ecosystem_461", "An ecosystem is a community of living organisms interacting with their environment."},
    {"antibody_462", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"biome_463", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"ecosystem_464", "An ecosystem is a community of living organisms interacting with their environment."},
    {"mitochondria_465", "Mitochondria are known as the powerhouse of the cell."},
    {"biome_466", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"antigen_467", "An antigen is a substance that induces an immune response."},
    {"ecosystem_468", "An ecosystem is a community of living organisms interacting with their environment."},
    {"chloroplast_469", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"antibody_470", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"biome_471", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"biome_472", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"mitochondria_473", "Mitochondria are known as the powerhouse of the cell."},
    {"chloroplast_474", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"transcription_475", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"ecosystem_476", "An ecosystem is a community of living organisms interacting with their environment."},
    {"chloroplast_477", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"ecosystem_478", "An ecosystem is a community of living organisms interacting with their environment."},
    {"transcription_479", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"antigen_480", "An antigen is a substance that induces an immune response."},
    {"translation_481", "Translation is the process where ribosomes create proteins using mRNA."},
    {"chloroplast_482", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"biome_483", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"transcription_484", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"nucleotide_485", "A nucleotide is the basic building block of DNA and RNA."},
    {"chloroplast_486", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"chloroplast_487", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"biome_488", "A biome is a large community of plants and animals that occupy a distinct region."},
    {"antibody_489", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"nucleotide_490", "A nucleotide is the basic building block of DNA and RNA."},
    {"nucleotide_491", "A nucleotide is the basic building block of DNA and RNA."},
    {"translation_492", "Translation is the process where ribosomes create proteins using mRNA."},
    {"antibody_493", "An antibody is a protein produced by the immune system to fight pathogens."},
    {"antigen_494", "An antigen is a substance that induces an immune response."},
    {"ecosystem_495", "An ecosystem is a community of living organisms interacting with their environment."},
    {"antigen_496", "An antigen is a substance that induces an immune response."},
    {"transcription_497", "Transcription is the process of copying a gene's DNA sequence into RNA."},
    {"nucleotide_498", "A nucleotide is the basic building block of DNA and RNA."},
    {"chloroplast_499", "Chloroplasts are organelles in plant cells that carry out photosynthesis."},
    {"nucleotide_500", "A nucleotide is the basic building block of DNA and RNA."},
};

#define EXTENDED_DICTIONARY_SIZE (sizeof(extended_dictionary) / sizeof(extended_dictionary[0]))
